version: '3.8'

services:
  nginx:
    ports:
      - "3000:80"  
  web:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=harman
      - MONGO_PASSWORD=1234
    command: ["npm", "run", "dev"]
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=harman
      - MONGO_INITDB_ROOT_PASSWORD=1234 

    
             
    

