version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  
  web:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=harman
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:        
              
     

